### ISSUE TITLE
Toggle English/Japanese output & local llm via oobabooga textgen webUI

### ISSUE THREAD

**Issue by MercyfulKing** [ZeroMirai/Waifu_AI_Vtuber#1]
Can this be updated to use english as an optional output also an option to select local llm connected to oobabooga textgen webUI?

**Comment by ZeroMirai** [comment]
@MercyfulKing Thanks for your feature request! It's indeed interesting about be able to use English as an optional output and an option to select local LLM, I'll add these features in an update plan. However, integrating Waifu_AI_Vtuber with the oobabooga textgen webUI might not align with the focus of the Waifu_AI_Vtuber, which its main focus is to communicate with users on streaming platforms. while oobabooga textgen webUI is a great tool, it might not fit the scope of this project. If you’re looking for a personal chatbot, you might want to check out [VirtuAI-Helper](https://github.com/ZeroMirai/VirtuAI-Helper), which might be more suitable for your needs. You can find more information about Waifu_AI_Vtuber and how it works in [README](https://github.com/ZeroMirai/Waifu_AI_Vtuber/blob/main/README.md). If you have any further questions or suggestions, feel free to open another issue.
